# Generated by Django 4.2.20 on 2025-04-02 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0002_remove_userprofile_birth_date_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
